### ISSUE TITLE
Improve doc for installing Drone-CI for Gitea on Docker

### ISSUE THREAD

**Issue by scls19fr** [go-gitea/docs#159]
Hello,

Currently I can see only 
http://docs.drone.io/install-for-gitea/
to install Drone-CI for Gitea (on Docker)
which is not very easy.

After tackling https://github.com/go-gitea/docs/issues/157 maybe a tutorial to install Drone-CI for Gitea (on Docker) will be a great improvement for inexperienced users (such I'm).

Kind regards

**Comment by lunny** [comment]
This should be at drone's document. See http://docs.drone.io/install-for-gitea/
