### ISSUE TITLE
Mention that /robots.txt can be managed by the user

### ISSUE THREAD

**Issue by sztanpet** [go-gitea/docs#66]
Willing to do the work of documenting the feature, but looking for guidance on where to do so.
The config cheat sheet does not seem appropriate for this.

**Comment by tboerger** [comment]
IMHO we got 2 options, add another chapter to `Advanced` or add another category like `Misc`

**Comment by bkcsoft** [comment]
This seems like Advanced usage, so just add a chapter there :)

**Comment by sztanpet** [comment]
yell if this warrants a backport :)

**Comment by lunny** [comment]
Yes, please
