### ISSUE TITLE
Add SHOW_FOOTER_TEMPLATE_LOAD_TIME 

### ISSUE THREAD

**Issue by rugk** [go-gitea/docs#70]
see https://github.com/go-gitea/gitea/issues/659

**Comment by tboerger** [comment]
Pull requests are welcome. I'm pretty sure there are also other options missing

**Comment by willemvd** [comment]
Are we going to add all options in the doc page?
There is already a reference to the app.ini jn GitHub
Do we want to maintain all the possible properties in 2 places or make the reference more clear?

**Comment by tboerger** [comment]
@willemvd some people want to add all options so that the description can get translated to all languages supported on the docs.

**Comment by avelino** [comment]
#87

**Comment by lunny** [comment]
resolved by #87
