### ISSUE TITLE
Website CSS broken

### ISSUE THREAD

**Issue by jmn** [go-gitea/docs#85]
Website styling is broken, at least on Chrome/Chromium.
See https://docs.gitea.io/en-us/install-with-docker/

![CSS Bug](https://cloud.githubusercontent.com/assets/35616/22271579/87887650-e295-11e6-9ece-6f27c80723c2.png)

**Comment by tboerger** [comment]
Wrong repo, this is related to the theme repo.

**Comment by jmn** [comment]
OK see https://github.com/go-gitea/theme/issues/31 - closing.
