### ISSUE TITLE
Problem with bountysource plugin?

### ISSUE THREAD

**Issue by jmn** [go-gitea/docs#86]
The plugin that generates new issue data appears like this:

![chrome_2017-01-25_04-30-51](https://cloud.githubusercontent.com/assets/35616/22276891/398c0e22-e2b7-11e6-8d46-3b751ad4dbdb.png)

When viewing issues https://github.com/go-gitea/docs/issues/

**Comment by lunny** [comment]
It seems yes. Don't know what's wrong.

**Comment by tboerger** [comment]
That's an upstream bug by bountysource. We can't fix that properly, we can just wait that they merge the pending pr.
